"""add_domain

Revision ID: 39f9df7b5774
Revises: c7267a60262e
Create Date: 2016-04-18 20:20:53.049686

"""

# revision identifiers, used by Alembic.
revision = '39f9df7b5774'
down_revision = 'c7267a60262e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('last_domain',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_domain')
    op.drop_table('domain')
    ### end Alembic commands ###
