"""add_link_to_hot_word

Revision ID: c7267a60262e
Revises: ff6c4638cce3
Create Date: 2016-04-11 16:44:27.049001

"""

# revision identifiers, used by Alembic.
revision = 'c7267a60262e'
down_revision = 'ff6c4638cce3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_word', sa.Column('link', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_word', 'link')
    ### end Alembic commands ###
