"""create_table_hot_word

Revision ID: ff6c4638cce3
Revises: 
Create Date: 2016-04-01 18:15:31.896317

"""

# revision identifiers, used by Alembic.
revision = 'ff6c4638cce3'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hot_word',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hot_word')
    ### end Alembic commands ###
